<?php

namespace App;

use App\Notifications\OrderCreated;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Notification;

class Order extends Model
{
    protected $guarded = [];


    public function products()
    {
        return $this->belongsToMany(Product::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function payment()
    {
        return $this->belongsTo(Pay::class);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($model) {
            $admins = User::where('type' , 'admin')->get();
            Notification::send($admins, new OrderCreated());
        });
    }
}
